---
abstract: 'Add a log() method to Git::Repository'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Cwd: '0'
  File::Find: '0'
  File::Spec: '0'
  File::Temp: '0'
  Test::Git: '0'
  Test::More: '0.88'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Repository-Plugin-Log
requires:
  Carp: '0'
  Git::Repository: '1.309'
  Git::Repository::Command: '0'
  Git::Repository::Plugin: '0'
  Scalar::Util: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Git-Repository-Plugin-Log
  repository: http://github.com/book/Git-Repository-Plugin-Log.git
version: '1.312'
